In [36]:
CRASH_API = "https://data.cityofnewyork.us/resource/h9gi-nx95.json"
VEHICLE_API = "https://data.cityofnewyork.us/resource/bm4k-52h4.json"
PERSON_API = "https://data.cityofnewyork.us/resource/f55k-p6yu.json"

In [4]:
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [32]:
def query_nyc_open_data(api_url, params=None):
    response = requests.get(
        api_url,
        params=params,
        timeout=240
    )
    response.raise_for_status()
    return pd.DataFrame(response.json())

In [16]:
vehicles_test = query_nyc_open_data(
    CRASH_API,
    {"$limit": 5}
)

print("Shape:", vehicles_test.shape)
vehicles_test

Shape: (5, 24)

,crash_date,crash_time,on_street_name,off_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,collision_id,vehicle_type_code1,vehicle_type_code2,borough,zip_code,latitude,longitude,location,contributing_factor_vehicle_3,vehicle_type_code_3
0,2021-09-11T00:00:00.000,2:39,WHITESTONE EXPRESSWAY,20 AVENUE,2,0,0,0,0,0,2,0,Aggressive Driving/Road Rage,Unspecified,4455765,Sedan,Sedan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-03-26T00:00:00.000,11:45,QUEENSBORO BRIDGE UPPER,NaN,1,0,0,0,0,0,1,0,Pavement Slippery,NaN,4513547,Sedan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-11-01T00:00:00.000,1:29,OCEAN PARKWAY,AVENUE K,1,0,0,0,0,0,1,0,Unspecified,Unspecified,4675373,Moped,Sedan,BROOKLYN,11230,40.62179,-73.970024,"{'latitude': '40.62179', 'longitude': '-73.970...",Unspecified,Sedan
3,2022-06-29T00:00:00.000,6:55,THROGS NECK BRIDGE,NaN,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-09-21T00:00:00.000,13:21,BROOKLYN BRIDGE,NaN,0,0,0,0,0,0,0,0,Passing Too Closely,Unspecified,4566131,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
print("Columns returned in the 5-row sample:")
for i, col in enumerate(test_df.columns, start=1):
    print(f"{i:2}. {col}")

Columns returned in the 5-row sample:
 1. crash_date
 2. crash_time
 3. on_street_name
 4. off_street_name
 5. number_of_persons_injured
 6. number_of_persons_killed
 7. number_of_pedestrians_injured
 8. number_of_pedestrians_killed
 9. number_of_cyclist_injured
10. number_of_cyclist_killed
11. number_of_motorist_injured
12. number_of_motorist_killed
13. contributing_factor_vehicle_1
14. contributing_factor_vehicle_2
15. collision_id
16. vehicle_type_code1
17. vehicle_type_code2
18. borough
19. zip_code
20. latitude
21. longitude
22. location
23. contributing_factor_vehicle_3
24. vehicle_type_code_3

In [18]:
vehicles_test = query_nyc_open_data(
    VEHICLE_API,
    {"$limit": 5}
)

print("Shape:", vehicles_test.shape)
vehicles_test

Shape: (5, 20)

,unique_id,collision_id,crash_date,crash_time,vehicle_id,state_registration,vehicle_type,contributing_factor_1,vehicle_make,vehicle_year,travel_direction,vehicle_occupants,driver_sex,driver_license_status,driver_license_jurisdiction,pre_crash,point_of_impact,vehicle_damage,public_property_damage,contributing_factor_2
0,10385780,100201,2012-09-07T00:00:00.000,9:03,1,NY,PASSENGER VEHICLE,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19140702,4213082,2019-09-23T00:00:00.000,8:15,0553ab4d-9500-4cba-8d98-f4d7f89d5856,NY,Station Wagon/Sport Utility Vehicle,Driver Inattention/Distraction,TOYT -CAR/SUV,2002,North,1,M,Licensed,NY,Going Straight Ahead,Left Front Bumper,Left Front Quarter Panel,N,Unspecified
2,14887647,3307608,2015-10-02T00:00:00.000,17:18,2,NY,TAXI,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Going Straight Ahead,NaN,NaN,NaN,NaN
3,14889754,3308693,2015-10-04T00:00:00.000,20:34,1,NY,PASSENGER VEHICLE,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parked,NaN,NaN,NaN,NaN
4,14400270,297666,2013-04-25T00:00:00.000,21:15,1,NY,PASSENGER VEHICLE,Other Vehicular,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
print("Columns returned in the 5-row sample:")

for i, col in enumerate(vehicles_test.columns, start=1):
    print(f"{i:2}. {col}")

Columns returned in the 5-row sample:
 1. unique_id
 2. collision_id
 3. crash_date
 4. crash_time
 5. vehicle_id
 6. state_registration
 7. vehicle_type
 8. contributing_factor_1
 9. vehicle_make
10. vehicle_year
11. travel_direction
12. vehicle_occupants
13. driver_sex
14. driver_license_status
15. driver_license_jurisdiction
16. pre_crash
17. point_of_impact
18. vehicle_damage
19. public_property_damage
20. contributing_factor_2

In [20]:
print("Crashes collision_id dtype:")
print(test_df["collision_id"].dtype)

print("\nVehicles collision_id dtype:")
print(vehicles_test["collision_id"].dtype)

Crashes collision_id dtype:
object

Vehicles collision_id dtype:
object

In [21]:
print("Crashes:")
print(test_df["collision_id"].head())

print("\nVehicles:")
print(vehicles_test["collision_id"].head())

Crashes:
0    4455765
1    4513547
2    4675373
3    4541903
4    4566131
Name: collision_id, dtype: object

Vehicles:
0     100201
1    4213082
2    3307608
3    3308693
4     297666
Name: collision_id, dtype: object

In [23]:
vehicles_test[["collision_id", "crash_date", "travel_direction"]]

  collision_id               crash_date travel_direction
0       100201  2012-09-07T00:00:00.000              NaN
1      4213082  2019-09-23T00:00:00.000            North
2      3307608  2015-10-02T00:00:00.000              NaN
3      3308693  2015-10-04T00:00:00.000              NaN
4       297666  2013-04-25T00:00:00.000              NaN

In [25]:
vehicles_sample = query_nyc_open_data(
    VEHICLE_API,
    {
        "$select": "collision_id,crash_date,travel_direction",
        "$limit": 10000
    }
)

print(vehicles_sample.shape)
vehicles_sample.head()

(10000, 3)

  collision_id               crash_date travel_direction
0       100201  2012-09-07T00:00:00.000              NaN
1      4213082  2019-09-23T00:00:00.000            North
2      3307608  2015-10-02T00:00:00.000              NaN
3      3308693  2015-10-04T00:00:00.000              NaN
4       297666  2013-04-25T00:00:00.000              NaN

In [26]:
vehicles_sample["travel_direction"].value_counts(dropna=False)

travel_direction
NaN          7409
East          633
North         603
West          544
South         540
Unknown        98
Northeast      43
Northwest      42
Southeast      40
Southwest      39
-               3
W               2
S               2
N               2
Name: count, dtype: int64

In [27]:
travel_direction_pct = (
    vehicles_sample["travel_direction"]
    .value_counts(dropna=False, normalize=True)
    .mul(100)
    .round(2)
)

travel_direction_pct

travel_direction
NaN          74.09
East          6.33
North         6.03
West          5.44
South         5.40
Unknown       0.98
Northeast     0.43
Northwest     0.42
Southeast     0.40
Southwest     0.39
-             0.03
W             0.02
S             0.02
N             0.02
Name: proportion, dtype: float64

In [28]:
recent_vehicles = query_nyc_open_data(
    VEHICLE_API,
    {
        "$select": "collision_id,crash_date,travel_direction",
        "$where": "crash_date >= '2024-01-01T00:00:00'",
        "$order": "crash_date DESC",
        "$limit": 10000
    }
)

print(recent_vehicles.shape)
recent_vehicles.head()

(10000, 3)

  collision_id               crash_date travel_direction
0      4905715  2026-06-11T00:00:00.000            North
1      4905771  2026-06-11T00:00:00.000            South
2      4905768  2026-06-11T00:00:00.000        Northeast
3      4905728  2026-06-11T00:00:00.000             East
4      4905729  2026-06-11T00:00:00.000             East

In [29]:
recent_direction_pct = (
    recent_vehicles["travel_direction"]
    .value_counts(dropna=False, normalize=True)
    .mul(100)
    .round(2)
)

recent_direction_pct

travel_direction
North        23.86
East         21.26
West         20.79
South        20.27
Unknown       9.29
Northeast     1.44
Southwest     1.06
Northwest     1.03
Southeast     1.00
Name: proportion, dtype: float64

In [30]:
def get_direction_sample(year, limit=10000):
    start_date = f"{year}-01-01T00:00:00"
    end_date = f"{year + 1}-01-01T00:00:00"

    df = query_nyc_open_data(
        VEHICLE_API,
        {
            "$select": "collision_id,crash_date,travel_direction",
            "$where": (
                f"crash_date >= '{start_date}' "
                f"AND crash_date < '{end_date}'"
            ),
            "$limit": limit
        }
    )

    return df

In [33]:
samples = {}

for year in range(2016, 2027):
    print(f"Downloading {year}...")
    samples[year] = get_direction_sample(year)

print("Done!")

Downloading 2016...
Downloading 2017...
Downloading 2018...
Downloading 2019...
Downloading 2020...
Downloading 2021...
Downloading 2022...
Downloading 2023...
Downloading 2024...
Downloading 2025...
Downloading 2026...
Done!

In [34]:
direction_quality = []

for year, df in samples.items():

    total = len(df)

    missing = df["travel_direction"].isna().sum()

    unknown = (
        df["travel_direction"]
        .astype(str)
        .str.strip()
        .str.lower()
        .eq("unknown")
        .sum()
    )

    direction_quality.append({
        "year": year,
        "sample_size": total,
        "missing_pct": missing / total * 100,
        "unknown_pct": unknown / total * 100
    })

direction_quality = pd.DataFrame(direction_quality)

direction_quality

    year  sample_size  missing_pct  unknown_pct
0   2016        10000        98.04         0.10
1   2017        10000         4.34         4.56
2   2018        10000         4.66         3.21
3   2019        10000         5.09         2.77
4   2020        10000         5.46         2.56
5   2021        10000         7.90         3.46
6   2022        10000         8.15         2.60
7   2023        10000         7.61         2.72
8   2024        10000         7.15         3.43
9   2025        10000         7.54         3.95
10  2026        10000         7.54         4.16

In [35]:
direction_quality = direction_quality[
    direction_quality["year"] >= 2017
].copy()

direction_quality["usable_direction_pct"] = (
    100
    - direction_quality["missing_pct"]
    - direction_quality["unknown_pct"]
)

direction_quality.round(2)

    year  sample_size  missing_pct  unknown_pct  usable_direction_pct
1   2017        10000         4.34         4.56                 91.10
2   2018        10000         4.66         3.21                 92.13
3   2019        10000         5.09         2.77                 92.14
4   2020        10000         5.46         2.56                 91.98
5   2021        10000         7.90         3.46                 88.64
6   2022        10000         8.15         2.60                 89.25
7   2023        10000         7.61         2.72                 89.67
8   2024        10000         7.15         3.43                 89.42
9   2025        10000         7.54         3.95                 88.51
10  2026        10000         7.54         4.16                 88.30

Person table

In [37]:
persons_test = query_nyc_open_data(
    PERSON_API,
    {"$limit": 5}
)

print("Shape:", persons_test.shape)
persons_test

Shape: (5, 17)

,unique_id,collision_id,crash_date,crash_time,person_id,person_type,person_injury,vehicle_id,ped_role,person_sex,person_age,ejection,emotional_status,bodily_injury,position_in_vehicle,safety_equipment,complaint
0,10249006,4229554,2019-10-26T00:00:00.000,9:43,31aa2bc0-f545-444f-8cdb-f1cb5cf00b89,Occupant,Unspecified,19141108,Registrant,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10255054,4230587,2019-10-25T00:00:00.000,15:15,4629e500-a73e-48dc-b8fb-53124d124b80,Occupant,Unspecified,19144075,Passenger,F,33,Not Ejected,Does Not Apply,Does Not Apply,"Front passenger, if two or more persons, inclu...",Lap Belt & Harness,Does Not Apply
2,10253177,4230550,2019-10-26T00:00:00.000,17:55,ae48c136-1383-45db-83f4-2a5eecfb7cff,Occupant,Unspecified,19143133,Registrant,M,55,NaN,NaN,NaN,NaN,NaN,NaN
3,6650180,3565527,2016-11-21T00:00:00.000,13:05,2782525,Occupant,Unspecified,NaN,Notified Person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10255516,4231168,2019-10-25T00:00:00.000,11:16,e038e18f-40fb-4471-99cf-345eae36e064,Occupant,Unspecified,19144329,Passenger,F,7,Not Ejected,Does Not Apply,Does Not Apply,Right rear passenger or motorcycle sidecar pas...,Lap Belt,Does Not Apply

In [38]:
print("Columns returned in the 5-row sample:")

for i, col in enumerate(persons_test.columns, start=1):
    print(f"{i:2}. {col}")

Columns returned in the 5-row sample:
 1. unique_id
 2. collision_id
 3. crash_date
 4. crash_time
 5. person_id
 6. person_type
 7. person_injury
 8. vehicle_id
 9. ped_role
10. person_sex
11. person_age
12. ejection
13. emotional_status
14. bodily_injury
15. position_in_vehicle
16. safety_equipment
17. complaint

In [39]:
print("Crashes collision_id dtype:")
print(test_df["collision_id"].dtype)

print("\nVehicles collision_id dtype:")
print(vehicles_test["collision_id"].dtype)

print("\nPersons collision_id dtype:")
print(persons_test["collision_id"].dtype)

Crashes collision_id dtype:
object

Vehicles collision_id dtype:
object

Persons collision_id dtype:
object

If a crash is corresponded to more than one person

In [40]:
persons_sample = query_nyc_open_data(
    PERSON_API,
    {
        "$select": "*",
        "$where": "crash_date >= '2017-01-01T00:00:00'",
        "$limit": 10000
    }
)

print("Rows:", len(persons_sample))
print("Unique collisions:", persons_sample["collision_id"].nunique())

Rows: 10000
Unique collisions: 2720

In [41]:
print(
    persons_sample["person_type"]
    .value_counts(dropna=False)
)

print()

print(
    persons_sample["person_injury"]
    .value_counts(dropna=False)
)

person_type
Occupant      9814
Pedestrian     122
Bicyclist       64
Name: count, dtype: int64

person_injury
Unspecified    9230
Injured         768
Killed            2
Name: count, dtype: int64

CRASHES
1 row ≈ 1 collision
location + severity + crash-level contributing factors
            │
            │ collision_id
            ▼
VEHICLES
multiple vehicles / collision
travel_direction
contributing_factor
pre_crash
point_of_impact
            │
            │ collision_id
            ▼
PERSONS
multiple persons / collision
person_type
person_injury
vehicle_id

In [42]:
print("Crashes collision_id dtype:")
print(test_df["collision_id"].dtype)

print("\nVehicles collision_id dtype:")
print(vehicles_test["collision_id"].dtype)

print("\nPersons collision_id dtype:")
print(persons_test["collision_id"].dtype)

Crashes collision_id dtype:
object

Vehicles collision_id dtype:
object

Persons collision_id dtype:
object

In [43]:
print("Missing collision_id:")
print(persons_sample["collision_id"].isna().sum())

print("\nMissing person_id:")
print(persons_sample["person_id"].isna().sum())

print("\nMissing vehicle_id:")
print(persons_sample["vehicle_id"].isna().sum())

Missing collision_id:
0

Missing person_id:
0

Missing vehicle_id:
241

In [44]:
persons_sample.groupby("person_type")["vehicle_id"].agg(
    total="size",
    missing=lambda x: x.isna().sum()
).assign(
    missing_pct=lambda x: x["missing"] / x["total"] * 100
).round(2)

             total  missing  missing_pct
person_type
Bicyclist       64        0         0.00
Occupant      9814      119         1.21
Pedestrian     122      122       100.00

In [45]:
linkage_crashes = query_nyc_open_data(
    CRASH_API,
    {
        "$select": """
            collision_id,
            crash_date,
            latitude,
            longitude,
            number_of_persons_injured,
            number_of_persons_killed
        """,
        "$where": (
            "crash_date >= '2025-01-01T00:00:00' "
            "AND crash_date < '2026-01-01T00:00:00'"
        ),
        "$limit": 1000
    }
)

print("Crash rows:", len(linkage_crashes))
print("Unique collision IDs:", linkage_crashes["collision_id"].nunique())
print("Missing collision IDs:", linkage_crashes["collision_id"].isna().sum())

Crash rows: 1000
Unique collision IDs: 1000
Missing collision IDs: 0

In [46]:
linkage_vehicles_all = query_nyc_open_data(
    VEHICLE_API,
    {
        "$select": """
            collision_id,
            vehicle_id,
            travel_direction,
            contributing_factor_1,
            contributing_factor_2,
            pre_crash,
            point_of_impact
        """,
        "$where": (
            "crash_date >= '2025-01-01T00:00:00' "
            "AND crash_date < '2026-01-01T00:00:00'"
        ),
        "$limit": 50000
    }
)

crash_ids = set(linkage_crashes["collision_id"])

linkage_vehicles = linkage_vehicles_all[
    linkage_vehicles_all["collision_id"].isin(crash_ids)
].copy()

print("Vehicle rows matched:", len(linkage_vehicles))
print("Crashes with vehicle records:",
      linkage_vehicles["collision_id"].nunique())

print("Crashes without vehicle records:",
      1000 - linkage_vehicles["collision_id"].nunique())

Vehicle rows matched: 1989
Crashes with vehicle records: 1000
Crashes without vehicle records: 0

In [47]:
linkage_persons_all = query_nyc_open_data(
    PERSON_API,
    {
        "$select": """
            collision_id,
            person_id,
            vehicle_id,
            person_type,
            person_injury,
            ped_role,
            person_age
        """,
        "$where": (
            "crash_date >= '2025-01-01T00:00:00' "
            "AND crash_date < '2026-01-01T00:00:00'"
        ),
        "$limit": 50000
    }
)

linkage_persons = linkage_persons_all[
    linkage_persons_all["collision_id"].isin(crash_ids)
].copy()

print("Person rows matched:", len(linkage_persons))
print("Crashes with person records:",
      linkage_persons["collision_id"].nunique())

print("Crashes without person records:",
      1000 - linkage_persons["collision_id"].nunique())

Person rows matched: 3340
Crashes with person records: 994
Crashes without person records: 6

how many vehicles are involved in one crash:

In [48]:
vehicles_per_crash = (
    linkage_vehicles
    .groupby("collision_id")
    .size()
)

print(vehicles_per_crash.describe())

print("\nVehicle count distribution:")
print(
    vehicles_per_crash
    .value_counts()
    .sort_index()
    .head(10)
)

count    1000.000000
mean        1.989000
std         0.635045
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         6.000000
dtype: float64

Vehicle count distribution:
1    160
2    730
3     78
4     26
5      5
6      1
Name: count, dtype: int64

In [49]:
persons_per_crash = (
    linkage_persons
    .groupby("collision_id")
    .size()
)

print(persons_per_crash.describe())

print("\nPerson count distribution:")
print(
    persons_per_crash
    .value_counts()
    .sort_index()
    .head(10)
)

count    994.000000
mean       3.360161
std        1.902736
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max       12.000000
dtype: float64

Person count distribution:
1     148
2     221
3     216
4     199
5      94
6      55
7      24
8      17
9       8
10      5
Name: count, dtype: int64

In [50]:
vehicle_summary = (
    linkage_vehicles
    .groupby("collision_id")
    .agg(
        n_vehicles=("vehicle_id", "size"),

        any_unsafe_speed=(
            "contributing_factor_1",
            lambda x: x.eq("Unsafe Speed").any()
        ),

        any_traffic_control_disregarded=(
            "contributing_factor_1",
            lambda x: x.eq("Traffic Control Disregarded").any()
        )
    )
    .reset_index()
)

vehicle_summary.head()

  collision_id  n_vehicles  any_unsafe_speed  any_traffic_control_disregarded
0      4783006           2             False                            False
1      4783024           2             False                            False
2      4783027           1             False                            False
3      4783038           2             False                            False
4      4783039           1              True                            False

In [51]:
print("Rows:", len(vehicle_summary))
print(
    "Unique collision IDs:",
    vehicle_summary["collision_id"].nunique()
)

vehicle_summary.head(10)

Rows: 1000
Unique collision IDs: 1000

  collision_id  n_vehicles  any_unsafe_speed  any_traffic_control_disregarded
0      4783006           2             False                            False
1      4783024           2             False                            False
2      4783027           1             False                            False
3      4783038           2             False                            False
4      4783039           1              True                            False
5      4783040           4              True                            False
6      4783041           2             False                            False
7      4783050           1             False                            False
8      4783055           4             False                            False
9      4783061           1             False                            False

In [53]:
person_summary = (
    linkage_persons
    .groupby("collision_id")
    .agg(
        n_persons=("person_id", "size"),

        n_injured=(
            "person_injury",
            lambda x: x.eq("Injured").sum()
        ),

        n_killed=(
            "person_injury",
            lambda x: x.eq("Killed").sum()
        ),

        n_pedestrians=(
            "person_type",
            lambda x: x.eq("Pedestrian").sum()
        ),

        n_bicyclists=(
            "person_type",
            lambda x: x.eq("Bicyclist").sum()
        )
    )
    .reset_index()
)

person_summary.head()

  collision_id  n_persons  n_injured  n_killed  n_pedestrians  n_bicyclists
0      4783006          5          0         0              0             0
1      4783024          4          0         0              0             0
2      4783027          7          0         0              0             0
3      4783038          2          0         0              0             0
4      4783039          2          1         0              0             0

In [54]:
print("Rows:", len(person_summary))
print(
    "Unique collision IDs:",
    person_summary["collision_id"].nunique()
)

person_summary.head(10)

Rows: 994
Unique collision IDs: 994

  collision_id  n_persons  n_injured  n_killed  n_pedestrians  n_bicyclists
0      4783006          5          0         0              0             0
1      4783024          4          0         0              0             0
2      4783027          7          0         0              0             0
3      4783038          2          0         0              0             0
4      4783039          2          1         0              0             0
5      4783040          6          0         0              0             0
6      4783041          4          0         0              0             0
7      4783050          4          2         0              0             0
8      4783055          3          1         0              0             0
9      4783061          3          1         0              0             0

In [55]:
crash_master = (
    linkage_crashes
    .merge(
        vehicle_summary,
        on="collision_id",
        how="left"
    )
    .merge(
        person_summary,
        on="collision_id",
        how="left"
    )
)

In [57]:
print("Rows:", len(crash_master))
print("Unique collision IDs:", crash_master["collision_id"].nunique())
print("Duplicate collision IDs:", crash_master["collision_id"].duplicated().sum())

crash_master.head(10)

Rows: 1000
Unique collision IDs: 1000
Duplicate collision IDs: 0

,collision_id,crash_date,latitude,longitude,number_of_persons_injured,number_of_persons_killed,n_vehicles,any_unsafe_speed,any_traffic_control_disregarded,n_persons,n_injured,n_killed,n_pedestrians,n_bicyclists
0,4783253,2025-01-01T00:00:00.000,40.66658,-73.939674,0,0,1,False,False,1.0,0.0,0.0,1.0,0.0
1,4783200,2025-01-01T00:00:00.000,40.589985,-73.95567,1,0,1,False,False,3.0,1.0,0.0,1.0,0.0
2,4783306,2025-01-01T00:00:00.000,40.570465,-74.109764,4,0,2,False,False,6.0,4.0,0.0,0.0,0.0
3,4783646,2025-01-01T00:00:00.000,40.556152,-74.21045,0,0,2,False,False,3.0,0.0,0.0,0.0,0.0
4,4783589,2025-01-01T00:00:00.000,40.655827,-73.981224,3,0,2,False,False,5.0,3.0,0.0,0.0,0.0
5,4783006,2025-01-01T00:00:00.000,40.810886,-73.88166,0,0,2,False,False,5.0,0.0,0.0,0.0,0.0
6,4783272,2025-01-01T00:00:00.000,0.0000000,0.0000000,1,0,2,False,False,3.0,1.0,0.0,0.0,0.0
7,4783795,2025-01-01T00:00:00.000,40.61074,-74.09583,0,0,2,False,False,4.0,0.0,0.0,0.0,0.0
8,4783696,2025-01-01T00:00:00.000,40.64872,-73.964905,1,0,2,False,False,4.0,1.0,0.0,0.0,1.0
9,4783040,2025-01-01T00:00:00.000,40.693787,-73.81173,0,0,4,True,False,6.0,0.0,0.0,0.0,0.0

In [58]:
crash_master[
    crash_master["n_persons"].isna()
][
    [
        "collision_id",
        "crash_date",
        "number_of_persons_injured",
        "number_of_persons_killed",
        "n_persons"
    ]
]

,collision_id,crash_date,number_of_persons_injured,number_of_persons_killed,n_persons
17,4783138,2025-01-01T00:00:00.000,0,0,NaN
96,4783610,2025-01-01T00:00:00.000,0,0,NaN
381,4785922,2025-01-02T00:00:00.000,0,0,NaN
611,4783606,2025-01-04T00:00:00.000,0,0,NaN
741,4784840,2025-01-04T00:00:00.000,0,0,NaN
770,4797016,2025-01-04T00:00:00.000,0,0,NaN

In [59]:
vehicle_crash = linkage_vehicles.merge(
    linkage_crashes[
        [
            "collision_id",
            "crash_date",
            "latitude",
            "longitude",
            "number_of_persons_injured",
            "number_of_persons_killed"
        ]
    ],
    on="collision_id",
    how="left",
    suffixes=("_vehicle", "_crash")
)

print("Rows:", len(vehicle_crash))
print(
    "Unique collision IDs:",
    vehicle_crash["collision_id"].nunique()
)
print(
    "Unique vehicle IDs:",
    vehicle_crash["vehicle_id"].nunique()
)

vehicle_crash.head(10)

Rows: 1989
Unique collision IDs: 1000
Unique vehicle IDs: 1989

,collision_id,vehicle_id,travel_direction,contributing_factor_1,contributing_factor_2,pre_crash,point_of_impact,crash_date,latitude,longitude,number_of_persons_injured,number_of_persons_killed
0,4783868,bd7ec171-ae2a-43db-a50e-207434f4264b,North,Driver Inattention/Distraction,Following Too Closely,Going Straight Ahead,Center Front End,2025-01-01T00:00:00.000,40.773018,-73.95219,0,0
1,4783269,8c52285b-8937-4b5f-95e8-bd6b6eac1d62,Unknown,Backing Unsafely,NaN,Entering Parked Position,Center Back End,2025-01-01T00:00:00.000,40.753483,-73.98089,0,0
2,4783066,9c214673-4269-4cc3-91e7-bc5a2999e817,South,Driver Inattention/Distraction,Driver Inattention/Distraction,Making Right Turn,Center Front End,2025-01-01T00:00:00.000,40.76249,-73.962975,1,0
3,4783215,366d0cbf-b3d3-4f19-bd3e-b3646eb0bf6d,South,Driver Inattention/Distraction,Driver Inattention/Distraction,Going Straight Ahead,Center Front End,2025-01-01T00:00:00.000,40.734314,-73.93802,1,0
4,4783686,1fb4665b-03fc-4f4c-903a-281087cd2c9a,East,Driver Inattention/Distraction,Unspecified,Making Left Turn,Right Rear Bumper,2025-01-01T00:00:00.000,40.67973,-73.93739,0,0
5,4783148,fe18bf60-31ec-4cac-9fe3-b06581887499,North,Driver Inattention/Distraction,Driver Inexperience,Going Straight Ahead,Left Front Quarter Panel,2025-01-01T00:00:00.000,40.711086,-73.95347,0,0
6,4783537,d5a6980f-27b7-4c91-a477-316abdd0c58c,East,Unspecified,Unspecified,Parked,Left Front Bumper,2025-01-01T00:00:00.000,40.879055,-73.87438,0,0
7,4783078,cfa683c6-1818-4498-8289-c74faf994def,North,Unspecified,Unspecified,Parked,Left Front Bumper,2025-01-01T00:00:00.000,40.628353,-73.94268,0,0
8,4783913,6bbea702-fa98-4a10-8ece-dd4ce045ce47,NaN,NaN,NaN,NaN,NaN,2025-01-01T00:00:00.000,40.60644,-73.97592,0,0
9,4783215,c2de92cc-8ac1-4b30-b1ca-bcfb9ef238c1,Northwest,Driver Inattention/Distraction,Driver Inattention/Distraction,Making Left Turn,Right Front Bumper,2025-01-01T00:00:00.000,40.734314,-73.93802,1,0

In [60]:
print("Total crashes:", len(crash_master))

print(
    "Missing latitude:",
    crash_master["latitude"].isna().sum()
)

print(
    "Missing longitude:",
    crash_master["longitude"].isna().sum()
)

print(
    "Zero coordinates:",
    (
        (pd.to_numeric(crash_master["latitude"], errors="coerce") == 0) |
        (pd.to_numeric(crash_master["longitude"], errors="coerce") == 0)
    ).sum()
)

Total crashes: 1000
Missing latitude: 16
Missing longitude: 16
Zero coordinates: 26

In [61]:
crash_master["latitude_num"] = pd.to_numeric(
    crash_master["latitude"],
    errors="coerce"
)

crash_master["longitude_num"] = pd.to_numeric(
    crash_master["longitude"],
    errors="coerce"
)

crash_master[
    ["latitude_num", "longitude_num"]
].describe()

       latitude_num  longitude_num
count    984.000000     984.000000
mean      39.643011     -71.968311
std        6.534720      11.862551
min        0.000000     -74.241936
25%       40.652757     -73.968479
50%       40.710035     -73.920485
75%       40.768512     -73.860839
max       40.905180       0.000000

In [62]:
crash_master["valid_coordinates"] = (
    crash_master["latitude_num"].notna()
    & crash_master["longitude_num"].notna()
    & (crash_master["latitude_num"] != 0)
    & (crash_master["longitude_num"] != 0)
)

crash_master["valid_coordinates"].value_counts()

valid_coordinates
True     958
False     42
Name: count, dtype: int64

In [63]:
crash_master["valid_coordinates"].value_counts(
    normalize=True
).mul(100).round(2)

valid_coordinates
True     95.8
False     4.2
Name: proportion, dtype: float64

In [64]:
crash_master["crash_injured"] = pd.to_numeric(
    crash_master["number_of_persons_injured"],
    errors="coerce"
)

crash_master["crash_killed"] = pd.to_numeric(
    crash_master["number_of_persons_killed"],
    errors="coerce"
)

In [65]:
consistency_check = crash_master[
    crash_master["n_persons"].notna()
].copy()

consistency_check["injury_match"] = (
    consistency_check["crash_injured"]
    == consistency_check["n_injured"]
)

consistency_check["killed_match"] = (
    consistency_check["crash_killed"]
    == consistency_check["n_killed"]
)

In [66]:
print("Crashes compared:", len(consistency_check))

print(
    "Injury matches:",
    consistency_check["injury_match"].sum()
)

print(
    "Injury mismatches:",
    (~consistency_check["injury_match"]).sum()
)

print(
    "Killed matches:",
    consistency_check["killed_match"].sum()
)

print(
    "Killed mismatches:",
    (~consistency_check["killed_match"]).sum()
)

Crashes compared: 994
Injury matches: 994
Injury mismatches: 0
Killed matches: 994
Killed mismatches: 0

In [70]:
vehicle_summary_new = (
    linkage_vehicles
    .assign(
        unsafe_speed=lambda df:
            df["contributing_factor_1"].eq("Unsafe Speed")
            | df["contributing_factor_2"].eq("Unsafe Speed"),

        traffic_control_disregarded=lambda df:
            df["contributing_factor_1"].eq("Traffic Control Disregarded")
            | df["contributing_factor_2"].eq("Traffic Control Disregarded")
    )
    .groupby("collision_id")
    .agg(
        n_vehicles=("vehicle_id", "size"),
        any_unsafe_speed=("unsafe_speed", "any"),
        any_traffic_control_disregarded=(
            "traffic_control_disregarded",
            "any"
        )
    )
    .reset_index()
)

In [71]:
print("Rows:", len(vehicle_summary_new))
print(
    "Unique collision IDs:",
    vehicle_summary_new["collision_id"].nunique()
)
print(
    "Crashes with Unsafe Speed:",
    vehicle_summary_new["any_unsafe_speed"].sum()
)
print(
    "Crashes with Traffic Control Disregarded:",
    vehicle_summary_new["any_traffic_control_disregarded"].sum()
)

Rows: 1000
Unique collision IDs: 1000
Crashes with Unsafe Speed: 80
Crashes with Traffic Control Disregarded: 47

In [72]:
crash_master_new = (
    linkage_crashes
    .merge(
        vehicle_summary_new,
        on="collision_id",
        how="left"
    )
    .merge(
        person_summary,
        on="collision_id",
        how="left"
    )
)

In [73]:
crash_master_new["latitude_num"] = pd.to_numeric(
    crash_master_new["latitude"],
    errors="coerce"
)

crash_master_new["longitude_num"] = pd.to_numeric(
    crash_master_new["longitude"],
    errors="coerce"
)

crash_master_new["valid_coordinates"] = (
    crash_master_new["latitude_num"].notna()
    & crash_master_new["longitude_num"].notna()
    & (crash_master_new["latitude_num"] != 0)
    & (crash_master_new["longitude_num"] != 0)
)

In [74]:
print("Rows:", len(crash_master_new))
print(
    "Unique collision IDs:",
    crash_master_new["collision_id"].nunique()
)
print(
    "Duplicate collision IDs:",
    crash_master_new["collision_id"].duplicated().sum()
)
print(
    "Valid coordinates:",
    crash_master_new["valid_coordinates"].sum()
)
print(
    "Unsafe Speed crashes:",
    crash_master_new["any_unsafe_speed"].sum()
)
print(
    "Traffic Control Disregarded crashes:",
    crash_master_new["any_traffic_control_disregarded"].sum()
)

Rows: 1000
Unique collision IDs: 1000
Duplicate collision IDs: 0
Valid coordinates: 958
Unsafe Speed crashes: 80
Traffic Control Disregarded crashes: 47

In [76]:
crash_master_new

,collision_id,crash_date,latitude,longitude,number_of_persons_injured,number_of_persons_killed,n_vehicles,any_unsafe_speed,any_traffic_control_disregarded,n_persons,n_injured,n_killed,n_pedestrians,n_bicyclists,latitude_num,longitude_num,valid_coordinates
0,4783253,2025-01-01T00:00:00.000,40.66658,-73.939674,0,0,1,False,False,1.0,0.0,0.0,1.0,0.0,40.666580,-73.939674,True
1,4783200,2025-01-01T00:00:00.000,40.589985,-73.95567,1,0,1,False,False,3.0,1.0,0.0,1.0,0.0,40.589985,-73.955670,True
2,4783306,2025-01-01T00:00:00.000,40.570465,-74.109764,4,0,2,False,False,6.0,4.0,0.0,0.0,0.0,40.570465,-74.109764,True
3,4783646,2025-01-01T00:00:00.000,40.556152,-74.21045,0,0,2,False,False,3.0,0.0,0.0,0.0,0.0,40.556152,-74.210450,True
4,4783589,2025-01-01T00:00:00.000,40.655827,-73.981224,3,0,2,False,False,5.0,3.0,0.0,0.0,0.0,40.655827,-73.981224,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4784202,2025-01-06T00:00:00.000,40.636982,-74.134094,0,0,2,False,False,4.0,0.0,0.0,0.0,0.0,40.636982,-74.134094,True
996,4784102,2025-01-06T00:00:00.000,40.888596,-73.89068,0,0,3,False,False,2.0,0.0,0.0,0.0,0.0,40.888596,-73.890680,True
997,4784515,2025-01-06T00:00:00.000,40.537746,-74.23286,0,0,2,False,False,3.0,0.0,0.0,0.0,0.0,40.537746,-74.232860,True
998,4784141,2025-01-06T00:00:00.000,40.685513,-73.84161,2,0,2,False,True,5.0,2.0,0.0,0.0,0.0,40.685513,-73.841610,True
999,4784271,2025-01-06T00:00:00.000,40.830524,-73.89561,2,0,4,False,False,3.0,2.0,0.0,0.0,0.0,40.830524,-73.895610,True

In [77]:
print("Crashes columns:")
print(linkage_crashes.columns.tolist())

print("\nVehicles columns:")
print(linkage_vehicles.columns.tolist())

print("\nPersons columns:")
print(linkage_persons.columns.tolist())

print("\nCrash master columns:")
print(crash_master_new.columns.tolist())

print("\nVehicle crash columns:")
print(vehicle_crash.columns.tolist())

Crashes columns:
['collision_id', 'crash_date', 'latitude', 'longitude', 'number_of_persons_injured', 'number_of_persons_killed']

Vehicles columns:
['collision_id', 'vehicle_id', 'travel_direction', 'contributing_factor_1', 'contributing_factor_2', 'pre_crash', 'point_of_impact']

Persons columns:
['collision_id', 'person_id', 'vehicle_id', 'person_type', 'person_injury', 'ped_role', 'person_age']

Crash master columns:
['collision_id', 'crash_date', 'latitude', 'longitude', 'number_of_persons_injured', 'number_of_persons_killed', 'n_vehicles', 'any_unsafe_speed', 'any_traffic_control_disregarded', 'n_persons', 'n_injured', 'n_killed', 'n_pedestrians', 'n_bicyclists', 'latitude_num', 'longitude_num', 'valid_coordinates']

Vehicle crash columns:
['collision_id', 'vehicle_id', 'travel_direction', 'contributing_factor_1', 'contributing_factor_2', 'pre_crash', 'point_of_impact', 'crash_date', 'latitude', 'longitude', 'number_of_persons_injured', 'number_of_persons_killed']

In [78]:
vehicle_crash

,collision_id,vehicle_id,travel_direction,contributing_factor_1,contributing_factor_2,pre_crash,point_of_impact,crash_date,latitude,longitude,number_of_persons_injured,number_of_persons_killed
0,4783868,bd7ec171-ae2a-43db-a50e-207434f4264b,North,Driver Inattention/Distraction,Following Too Closely,Going Straight Ahead,Center Front End,2025-01-01T00:00:00.000,40.773018,-73.95219,0,0
1,4783269,8c52285b-8937-4b5f-95e8-bd6b6eac1d62,Unknown,Backing Unsafely,NaN,Entering Parked Position,Center Back End,2025-01-01T00:00:00.000,40.753483,-73.98089,0,0
2,4783066,9c214673-4269-4cc3-91e7-bc5a2999e817,South,Driver Inattention/Distraction,Driver Inattention/Distraction,Making Right Turn,Center Front End,2025-01-01T00:00:00.000,40.76249,-73.962975,1,0
3,4783215,366d0cbf-b3d3-4f19-bd3e-b3646eb0bf6d,South,Driver Inattention/Distraction,Driver Inattention/Distraction,Going Straight Ahead,Center Front End,2025-01-01T00:00:00.000,40.734314,-73.93802,1,0
4,4783686,1fb4665b-03fc-4f4c-903a-281087cd2c9a,East,Driver Inattention/Distraction,Unspecified,Making Left Turn,Right Rear Bumper,2025-01-01T00:00:00.000,40.67973,-73.93739,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1984,4784245,2a7c318d-4158-4552-8b44-e26c178322ac,South,Unspecified,Unspecified,Making Left Turn,Right Rear Quarter Panel,2025-01-06T00:00:00.000,40.64063,-74.02573,0,0
1985,4784272,bb7a89ab-90bc-448f-b4a0-29c712dfc404,South,Pavement Slippery,Driver Inattention/Distraction,Going Straight Ahead,Center Front End,2025-01-06T00:00:00.000,40.719337,-73.985916,2,0
1986,4784439,7e32943e-66f2-4255-be3a-6fa62a05f4e5,North,Unspecified,NaN,Entering Parked Position,No Damage,2025-01-06T00:00:00.000,40.653683,-73.93254,0,0
1987,4784609,410923ee-edd3-45d6-bd48-5f25da812fa6,NaN,NaN,NaN,NaN,NaN,2025-01-06T00:00:00.000,40.621635,-74.00963,0,0
1988,4784399,8f6b9b82-bd36-44b2-adae-bc460158f99b,East,Driver Inattention/Distraction,Unspecified,Making Right Turn,Right Front Bumper,2025-01-06T00:00:00.000,40.597267,-73.99866,1,0